<#include "commons/barcode.ftl">
<#include "commons/qrcode.ftl">
<#include "commons/title_setting.ftl">
<#include "commons/bar_setting.ftl">
<#include "commons/line_setting.ftl">
<#include "commons/pie_setting.ftl">
<#include "commons/margin_setting.ftl">
<#include "commons/funnel_setting.ftl">
<#include "commons/pictorial_setting.ftl">
<#include "commons/scatter_setting.ftl">
<#include "commons/map_setting.ftl">
<#include "commons/radar_setting.ftl">
<#include "commons/gauge_setting.ftl">
<#include "commons/xAxis_setting.ftl">
<#include "commons/yAxis_setting.ftl">
<#include "commons/series_setting.ftl">
<#include "commons/tooltip_setting.ftl">
<#include "commons/grid_setting.ftl">
<#include "commons/legend_setting.ftl">
<#include "commons/background_setting.ftl">
<#include "commons/match_setting.ftl">
<#include "commons/data_source_setting.ftl">
<#include "commons/central_point_setting.ftl">